#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "CtrlFlow"
  https://create.arduino.cc/cloud/things/2b50c770-2df2-4277-86ca-9e936612871b 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperature temperature2;
  CloudTemperature temperature1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <string>

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
}




void onTemperature1Change() {
  // char cstr[16];
  // itoa(temperature1, cstr, 10);
  String cstr = String((int)temperature1);
  String output = "Bedroom 1: " + cstr;
  Serial.println(output);
}


void onTemperature2Change() {
  // char cstr[16];
  // itoa(temperature2, cstr, 10);
  String cstr = String((int)temperature2);
  String output = "Bedroom 2: " + cstr;
  Serial.println(output);
}



